<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SHORTS</name>
   <tag></tag>
   <elementGuidId>2537af7d-bdd7-43f4-a37d-f7acdddc4834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menusidebarleft > li:nth-of-type(5) > a[title=&quot;SHORTS&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menusidebarleft']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba764dbe-3016-4b36-b799-0a762da5adcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/shorts</value>
      <webElementGuid>6b6e7aec-d3ae-4bd5-adfb-fea142331229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SHORTS</value>
      <webElementGuid>1a26db49-87fd-4207-b412-99b474eb47fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHORTS</value>
      <webElementGuid>e25ffb2b-f462-4bbd-a808-a4da0584c633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menusidebarleft&quot;)/li[5]/a[1]</value>
      <webElementGuid>821ad933-bb49-4744-80ba-85af6f96bdc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menusidebarleft']/li[5]/a</value>
      <webElementGuid>9003c88e-8883-4695-8262-46a9705306ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SHORTS')])[2]</value>
      <webElementGuid>32d714b3-b332-4c7d-9994-270e82e0fb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOODIES'])[3]/following::a[1]</value>
      <webElementGuid>662c6ca1-698e-460b-bd58-75547592d700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SWEATERS'])[2]/following::a[2]</value>
      <webElementGuid>3380f2c6-3d3a-42ed-818a-71be2aa557b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERFUME'])[2]/preceding::a[1]</value>
      <webElementGuid>d6baa4a1-50e6-47e1-a117-fd12261a743d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JACKET'])[2]/preceding::a[2]</value>
      <webElementGuid>a728c870-ba02-4c14-99df-c750486b42a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/shorts')])[2]</value>
      <webElementGuid>47b7a518-21f5-4e0d-a60d-899e550bae84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]/a</value>
      <webElementGuid>96b97d0b-6a3d-4552-9cc6-4212dab76bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/shorts' and @title = 'SHORTS' and (text() = 'SHORTS' or . = 'SHORTS')]</value>
      <webElementGuid>2a61cc7b-88b4-432d-b428-93577cb15686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
