<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACCESSORIES</name>
   <tag></tag>
   <elementGuidId>50bbe6b9-0307-48a1-b57c-28e18a8e5c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menusidebarleft > li:nth-of-type(8) > a[title=&quot;ACCESSORIES&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menusidebarleft']/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2628f8e5-f84d-4f29-86b3-c974d9997a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/accessories</value>
      <webElementGuid>4ab63e63-e7ab-48e5-ac5a-a0c0c4f6acbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ACCESSORIES</value>
      <webElementGuid>d16bdf5d-6dd5-494f-855a-36f4d6fba002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCESSORIES</value>
      <webElementGuid>4ee7eacd-0c5d-42d6-af74-6f65690ab3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menusidebarleft&quot;)/li[8]/a[1]</value>
      <webElementGuid>9b94a3ab-f59b-46f3-aac5-261aa9cd1249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menusidebarleft']/li[8]/a</value>
      <webElementGuid>71c68af2-b586-4afe-8437-7e8fb4d9144e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ACCESSORIES')])[2]</value>
      <webElementGuid>55349bd4-bd68-4c97-94c4-013e8849bd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JACKET'])[3]/following::a[1]</value>
      <webElementGuid>96ff392e-e9bc-4564-980e-b702ca16db8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERFUME'])[2]/following::a[2]</value>
      <webElementGuid>63a862f8-73ea-44f3-aea2-81c8e9398d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLO'])[2]/preceding::a[1]</value>
      <webElementGuid>39aba92a-9ee1-4ddc-b870-78298cf6c42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PANTS'])[2]/preceding::a[2]</value>
      <webElementGuid>751d592d-7bdc-4f3c-aa7a-6e4b87d31209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/accessories')])[2]</value>
      <webElementGuid>42418089-36bc-4253-83b3-19acd7e7108a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[8]/a</value>
      <webElementGuid>e65cda46-fb8f-4738-a8cc-e8581b58a71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/accessories' and @title = 'ACCESSORIES' and (text() = 'ACCESSORIES' or . = 'ACCESSORIES')]</value>
      <webElementGuid>2889ebde-5908-438b-bade-f931aee81f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
