<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_giy_dt-width-100 ls-is-cached lazyloaded</name>
   <tag></tag>
   <elementGuidId>49a3a0c9-0ddc-414f-9763-aa827cd072d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img_first > img.dt-width-100.ls-is-cached.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='group-sale-index']/div[2]/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02e1b7b6-94ce-41f0-ae6c-26937aa47c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-width-100 ls-is-cached lazyloaded</value>
      <webElementGuid>27fb79c7-94c5-43e3-80e6-b95f6541f1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>29336c1d-9b45-4f5c-8b44-09df44bc1db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>d531824d-5918-4053-9a1c-c3d545ee6d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg</value>
      <webElementGuid>58ee35f1-c478-4613-b493-ad0fc15439b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg</value>
      <webElementGuid>f6737566-dcf7-453a-b171-9b78927133ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Simple T-Shirt/Cream</value>
      <webElementGuid>f4fa996e-d122-4923-b7fe-f53df9101303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-sale-index&quot;)/div[@class=&quot;row box-product-lists&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-sm-4 col-xs-6 product-wrapper product-resize mb30 fixheight&quot;]/div[@class=&quot;product-information&quot;]/div[@class=&quot;product-detail clearfix&quot;]/div[@class=&quot;product-image image-resize&quot;]/a[1]/div[@class=&quot;img_first&quot;]/img[@class=&quot;dt-width-100 ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>29f8392c-7414-4498-9d21-24a53b9a6ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-sale-index']/div[2]/div/div/div/div/a/div/img</value>
      <webElementGuid>6e900eb3-d5eb-4807-b373-2f947a760fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Simple T-Shirt/Cream']</value>
      <webElementGuid>0a88feb0-adf1-4586-b675-b174a4d361c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b23a0cfb-69a4-4e08-8d35-5915208c81ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg' and @alt = 'Simple T-Shirt/Cream']</value>
      <webElementGuid>b167c7a6-e4fa-46cc-b998-c39d5e738866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
