<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PANTS</name>
   <tag></tag>
   <elementGuidId>fa274d54-b3bc-430a-be79-ce37a20e6978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menusidebarleft > li:nth-of-type(10) > a[title=&quot;PANTS&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menusidebarleft']/li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d0389b6-3737-49b1-8859-5f2edb7d1be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/pants</value>
      <webElementGuid>ead27cc9-8ffd-4e90-a67a-5a13e0c73105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PANTS</value>
      <webElementGuid>a226707c-0a11-44fb-80bd-b45b4008512a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANTS</value>
      <webElementGuid>c8d78b83-acb8-46e9-ab74-a5c2e8cdde6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menusidebarleft&quot;)/li[10]/a[1]</value>
      <webElementGuid>462f08fd-0c27-4a2f-9194-79378b6aba3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menusidebarleft']/li[10]/a</value>
      <webElementGuid>1ca686c3-22ee-477c-868e-cf2a9b663ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'PANTS')])[2]</value>
      <webElementGuid>bde9fae4-852b-4005-870d-015c9e27bc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLO'])[3]/following::a[1]</value>
      <webElementGuid>bda30698-76b2-4e2f-be1b-94672f04566c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESSORIES'])[2]/following::a[2]</value>
      <webElementGuid>b5ae1144-afb4-4044-80ee-e1e00ee0f34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLO'])[4]/preceding::a[1]</value>
      <webElementGuid>cfe46791-4ce2-42f2-a231-44071a010528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo:'])[1]/preceding::a[1]</value>
      <webElementGuid>1422ee4e-9a7f-46d9-94ca-fc78c0155d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/pants')])[2]</value>
      <webElementGuid>53a4ea1a-b545-436b-bcde-87e9c3bb66eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[10]/a</value>
      <webElementGuid>2f0b1055-80cd-47a2-9293-fda86246cb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/pants' and @title = 'PANTS' and (text() = 'PANTS' or . = 'PANTS')]</value>
      <webElementGuid>3d612b52-28ff-45f4-810c-a025a962bde9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
