<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_POLO</name>
   <tag></tag>
   <elementGuidId>c174657f-41ec-4fd3-9577-07f50fbd7e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box-wrapper']/main/div/div/div/div/ol/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>30bcd2b5-6b87-4fed-b3d0-009b7419fac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>d205523f-adf2-4e4a-ac88-1f39942dc31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>POLO</value>
      <webElementGuid>bfeb4353-b311-48e9-beb4-4e099600ecc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-wrapper&quot;)/main[1]/div[@class=&quot;header-navigate clearfix mb15&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 pd5&quot;]/ol[@class=&quot;breadcrumb breadcrumb-arrow&quot;]/li[@class=&quot;active&quot;]</value>
      <webElementGuid>250a499b-7f74-4249-b78d-e99c8b7d3257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-wrapper']/main/div/div/div/div/ol/li[5]</value>
      <webElementGuid>1ac6b88f-f8ae-4bca-81ce-7bbe37ffba09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::li[2]</value>
      <webElementGuid>765cd2c1-cc3c-4b7b-8c2d-1b2021783d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::li[4]</value>
      <webElementGuid>2b54ce75-7d28-4289-95d2-353e15a82871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục nhóm'])[1]/preceding::li[1]</value>
      <webElementGuid>4542f4bf-638c-4cd0-9fd3-1396c942bc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[5]</value>
      <webElementGuid>8eaec20f-11fa-4c71-bc98-1de7ede7aa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'POLO' or . = 'POLO')]</value>
      <webElementGuid>afaa0a0e-b7cb-426c-b6cb-1df13d999063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
