<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JACKET</name>
   <tag></tag>
   <elementGuidId>80e26b40-da37-4479-b1be-1385cc50345c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menusidebarleft > li:nth-of-type(7) > a[title=&quot;JACKET&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menusidebarleft']/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e5ef0c1-b3a8-466e-85f5-98959763dbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/jacket</value>
      <webElementGuid>b21de7dc-ba39-46e3-8ee5-d5a77b3500e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>JACKET</value>
      <webElementGuid>9a63d081-f2cc-4dde-8a92-b065d8b5f827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JACKET</value>
      <webElementGuid>7da7795d-ea38-4562-b2ff-b5babd31bbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menusidebarleft&quot;)/li[7]/a[1]</value>
      <webElementGuid>3a4b54df-8715-42c5-a2ef-f26ac61d31e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menusidebarleft']/li[7]/a</value>
      <webElementGuid>fa1f3eaf-985d-4573-b2f2-2f79d5ed9974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'JACKET')])[2]</value>
      <webElementGuid>e08c9960-d56f-4c8e-bccb-84eb52f49da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERFUME'])[3]/following::a[1]</value>
      <webElementGuid>9e921f37-8828-4232-8526-3bdfc7195fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHORTS'])[2]/following::a[2]</value>
      <webElementGuid>9c0a8aea-ae3c-4cd9-9497-1873b8785bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESSORIES'])[2]/preceding::a[1]</value>
      <webElementGuid>46575ad4-5baa-4949-91c4-3f866359f53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLO'])[2]/preceding::a[2]</value>
      <webElementGuid>07042574-a7c3-4a78-a227-be7e978ad7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/jacket')])[2]</value>
      <webElementGuid>2b8818c9-ac49-4680-bb99-2278c7ae42b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[7]/a</value>
      <webElementGuid>e97d7c16-3a42-4201-a714-bba1982aa1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/jacket' and @title = 'JACKET' and (text() = 'JACKET' or . = 'JACKET')]</value>
      <webElementGuid>efc5a341-80fb-4d47-aca5-93fa7622aef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
