<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOME</name>
   <tag></tag>
   <elementGuidId>9fb7aa86-5308-4fb2-befc-3307a3eca0a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;HOME&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar']/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2bb045d1-500f-41de-bd06-54d118207266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>5f10ead4-a3eb-4de8-9c35-698d986b3bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>f2ade8ae-47d5-4b6f-9aa0-da5a4bc0c148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>45b11d3e-bb48-43d6-b9e4-15307e3b3444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/ul[@class=&quot;nav navbar-nav clearfix flexbox-grid flexbox-justifyContent-center&quot;]/li[@class=&quot;open&quot;]/a[1]</value>
      <webElementGuid>6a3f1546-5936-4070-a404-e0dcf5337f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div/ul/li/a</value>
      <webElementGuid>1591088a-1723-437b-9672-b3f6fad991b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOME')]</value>
      <webElementGuid>a5a3c8bf-7bce-4ab7-97e8-1f1f0c70f0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[8]</value>
      <webElementGuid>19ece9d8-8169-4ab4-82d3-9b6923d9eec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP'])[1]/preceding::a[1]</value>
      <webElementGuid>6ab01d98-b327-4d2b-afa8-3c8081d8d421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-SHIRTS'])[1]/preceding::a[2]</value>
      <webElementGuid>d6bbe83c-0c7a-460c-8cc7-48372a9ff966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HOME']/parent::*</value>
      <webElementGuid>850f810a-2f8b-49fd-8d41-f9d6d2e9536c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[6]</value>
      <webElementGuid>78c44c91-4d37-40ff-8546-e845e813222b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/ul/li/a</value>
      <webElementGuid>03ef5e12-cbc6-46c1-a3a3-bac99eadbb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and @title = 'HOME' and (text() = 'HOME' or . = 'HOME')]</value>
      <webElementGuid>98497b9f-91da-482f-a63c-432821b055e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
