<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a ch_billing_addressaddress1</name>
   <tag></tag>
   <elementGuidId>f53258ce-9f09-4ce4-86fe-2aab2cbecd8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_address_address1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_address_address1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bed97794-4c53-42a8-9ac2-9aad23c1da3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ</value>
      <webElementGuid>41e00e4d-cd8f-4352-9d6b-92e2101f12cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>34c6cc15-bfbd-4e48-bc91-dbf1b66a4911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d22538fb-42ed-403c-8d68-968de7ac23a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-input</value>
      <webElementGuid>5e1c9602-10b5-4418-b2bb-b97d222c340a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>425efa73-8303-4213-b1be-ff596bc475a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>972bcde5-b8c1-4fef-8980-9467c47327ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_address_address1</value>
      <webElementGuid>864bf16c-70fa-4082-b415-f9520ab95f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address[address1]</value>
      <webElementGuid>0b921bc4-337a-4693-a335-a77013dbfe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_address_address1&quot;)</value>
      <webElementGuid>41671205-22d7-4804-b4f5-6f8d8e63bfcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_address_address1']</value>
      <webElementGuid>15842410-bfb2-4c94-a93e-ed61e0e080ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_update_location_customer_shipping']/div[2]/div/input</value>
      <webElementGuid>b6745afb-d83d-4b6d-b5cb-d06085c3581e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/input</value>
      <webElementGuid>fcf4dc16-8457-4ff6-9fa0-f3b4f7027b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Địa chỉ' and @type = 'text' and @id = 'billing_address_address1' and @name = 'billing_address[address1]']</value>
      <webElementGuid>4b0826da-2fcb-45af-9910-1e3f170f7518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
