<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PERFUME</name>
   <tag></tag>
   <elementGuidId>42e0b728-8dc9-4576-ad32-3d63ad0e6941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menusidebarleft > li:nth-of-type(6) > a[title=&quot;PERFUME&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menusidebarleft']/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0359bcad-ca26-44b7-bac7-be01931ed41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/perfume</value>
      <webElementGuid>f365d9c3-e379-4d10-872d-3bd98a2cb505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PERFUME</value>
      <webElementGuid>d4d80e60-84bf-4154-a1d5-8b05ba313e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PERFUME</value>
      <webElementGuid>ed534475-0eff-441e-afc2-155cc38e0a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menusidebarleft&quot;)/li[6]/a[1]</value>
      <webElementGuid>29a5fc40-bbcb-4303-ab02-d90599a864d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menusidebarleft']/li[6]/a</value>
      <webElementGuid>960a52f2-0aac-4411-99ef-802d1aef4411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'PERFUME')])[2]</value>
      <webElementGuid>9798e5d3-54d2-4ad6-80c0-dc26e283eb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHORTS'])[3]/following::a[1]</value>
      <webElementGuid>e7e3f7de-e6bb-4c72-abd4-bc722f3d837f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOODIES'])[2]/following::a[2]</value>
      <webElementGuid>82ace27c-df59-4854-92f2-413c7971eb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JACKET'])[2]/preceding::a[1]</value>
      <webElementGuid>55eb174f-716d-424d-88bd-a2a8df7c3889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESSORIES'])[2]/preceding::a[2]</value>
      <webElementGuid>7bdb7b6c-9c4a-4922-8cbf-130e8a80fc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/perfume')])[2]</value>
      <webElementGuid>5b04b430-84bb-443c-bd2a-ca121318d86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[6]/a</value>
      <webElementGuid>0c361df7-7d41-478d-b88f-9c093017c1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/perfume' and @title = 'PERFUME' and (text() = 'PERFUME' or . = 'PERFUME')]</value>
      <webElementGuid>c3aa5b39-84c3-4bd0-979c-a9183dc0f45f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
