<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng k_customerfirst_name</name>
   <tag></tag>
   <elementGuidId>76ecfe92-567d-42cd-89db-6c869c74c725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first_name > #first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a70f7dc-daac-48d1-8a8e-ac46adae9791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8c87a6b-fa06-451a-94f1-d2e29e03ae00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[first_name]</value>
      <webElementGuid>82131605-70d9-49c3-b43d-ed70bd89ce84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên</value>
      <webElementGuid>b0a2a5ef-cf86-4bca-b5bf-af04e80ba811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>90deeff5-386a-4381-a76f-9f4330c9e296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0cc99f7-1174-4354-bf5c-6ec1985c1da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d1180d8c-b2b4-43ee-851e-a02e46bcaaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_customer&quot;)/div[@id=&quot;first_name&quot;]/input[@id=&quot;first_name&quot;]</value>
      <webElementGuid>1a659afd-6a91-41f2-9c4a-f7e630d99e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first_name']</value>
      <webElementGuid>694ec958-59bb-4458-8306-5ea5ed2d299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='first_name']/input</value>
      <webElementGuid>c1cfcd2f-6d43-42d3-8a90-60be12980f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e49d28d5-71cb-498b-8960-b3cf81f07b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer[first_name]' and @placeholder = 'Tên' and @id = 'first_name']</value>
      <webElementGuid>41a7d610-0126-43f5-8285-984c4b136f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
