<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng k_btn (1)</name>
   <tag></tag>
   <elementGuidId>c3ccba6d-b060-4922-8649-51baa635aef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Đăng ký']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5df1555b-24bc-4d85-b2c7-c1457526b89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>226a2af6-6c80-4835-9017-3fa9c067f76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fa6316ab-45e9-455b-8ec9-21988e5b86bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>db2b1629-5621-4966-b8d1-c736ec0c8004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_customer&quot;)/div[@class=&quot;action_bottom mb15&quot;]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>2b5c7b8f-5de1-4b0f-bea2-47f1ed4cee04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Đăng ký']</value>
      <webElementGuid>626802ec-c2e4-4f14-bc69-b24e03aedc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[5]/input</value>
      <webElementGuid>8ebde370-381c-4a8c-9ad2-9f06bacd042f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>327dfcfb-65c2-49f1-9bf4-95b6c2f778b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>29cbfa96-10cf-4818-84ae-9e7402b838c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
