<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Email  tn ti. Nu bn qun mt khu, bn c th _48cf7e (1)</name>
   <tag></tag>
   <elementGuidId>1af49c97-d037-409f-9298-002693640f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.errors > ul > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='create_customer']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ea882a4f-2175-48fb-b05f-e60d27d14162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email đã tồn tại. Nếu bạn quên mật khẩu, bạn có thể thiết lập lại mật khẩu tại đây.</value>
      <webElementGuid>47e3278d-4d7a-4921-9e25-d8b9c08cfd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_customer&quot;)/div[@class=&quot;errors&quot;]/ul[1]/li[1]</value>
      <webElementGuid>754895b8-4214-4bd6-a1a2-aab131b37fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div/ul/li</value>
      <webElementGuid>7051db32-ab11-4fdb-8b02-1b06dd8e6225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/following::li[1]</value>
      <webElementGuid>b8ac71cd-569a-4b9a-84c4-ad007c92ad85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ðăng ký'])[1]/following::li[1]</value>
      <webElementGuid>fb659424-2d8f-48e4-bef2-a0b9f54589c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay về'])[1]/preceding::li[1]</value>
      <webElementGuid>b77605bb-7646-406e-8dec-37b789a098ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email đã tồn tại. Nếu bạn quên mật khẩu, bạn có thể']/parent::*</value>
      <webElementGuid>acfda59a-2788-4a7c-9b6c-bbaafad2a5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/ul/li</value>
      <webElementGuid>a918a268-8420-41c7-bb4b-78e98200843f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Email đã tồn tại. Nếu bạn quên mật khẩu, bạn có thể thiết lập lại mật khẩu tại đây.' or . = 'Email đã tồn tại. Nếu bạn quên mật khẩu, bạn có thể thiết lập lại mật khẩu tại đây.')]</value>
      <webElementGuid>5bffa0d7-923d-4df4-ada8-2a192f624929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
