<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng k</name>
   <tag></tag>
   <elementGuidId>07af075b-5954-4f7a-9ce3-e8eabcb12dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Đăng ký&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customer_login']/div[4]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c740c0b-a46b-47b3-b7e4-a348a49f0ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/register</value>
      <webElementGuid>25bc5519-e2e3-4cc7-93db-5af6f8847d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>33098023-df11-4448-a5a1-9b7bbca846ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>558595a8-a281-4fe7-9436-d2d084c13576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;req_pass&quot;]/a[2]</value>
      <webElementGuid>a30940cd-12de-4db9-a9e6-44485059d774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[4]/a[2]</value>
      <webElementGuid>7754facd-669a-4b38-83bb-98fcc07eab8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng ký')]</value>
      <webElementGuid>4087cb51-f970-48ee-98da-833379916775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/following::a[2]</value>
      <webElementGuid>12fd03b5-74c9-419f-9cc7-7a32514e746e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phục hồi mật khẩu'])[1]/preceding::a[1]</value>
      <webElementGuid>e9d1c754-97b4-4e9c-8099-8cedf90653ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin liên hệ:'])[1]/preceding::a[2]</value>
      <webElementGuid>c318cd33-f692-4c91-87e4-fec7d5a16f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng ký']/parent::*</value>
      <webElementGuid>63908cd2-c724-478d-bdd9-806ffec5ae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/register')]</value>
      <webElementGuid>8bfb1cd0-fca9-4bb0-93ae-4a90ebb637e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>caf5c22b-a40b-4f93-97fb-82bcbf27a592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/register' and @title = 'Đăng ký' and (text() = 'Đăng ký' or . = 'Đăng ký')]</value>
      <webElementGuid>fe7619a1-fbde-4820-b01d-26ae03ef919d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
