<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_T-SHIRTS</name>
   <tag></tag>
   <elementGuidId>6458d10c-f970-48e5-a3fa-49cb7af1fb14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box-wrapper']/main/div/div/div/div/ol/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>787b49b2-5b88-4d9b-9c22-57dd1824774d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>b53a8b05-44bb-4fa9-9eb1-06cf9523c332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T-SHIRTS</value>
      <webElementGuid>907c1e71-b5bd-422f-85c3-eb802fe5cf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-wrapper&quot;)/main[1]/div[@class=&quot;header-navigate clearfix mb15&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 pd5&quot;]/ol[@class=&quot;breadcrumb breadcrumb-arrow&quot;]/li[@class=&quot;active&quot;]</value>
      <webElementGuid>16208632-6ee8-46a3-8546-0484ca8380d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-wrapper']/main/div/div/div/div/ol/li[5]</value>
      <webElementGuid>4d7059a6-00ce-4d58-a3a4-eb2e7fa7a324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::li[2]</value>
      <webElementGuid>b57f5543-6295-4466-bee2-ef9ef4ecbdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::li[4]</value>
      <webElementGuid>109d7998-1ea6-44ed-bc9e-75c5fad9fb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục nhóm'])[1]/preceding::li[1]</value>
      <webElementGuid>8e9fef96-f6d8-4e44-be58-f9c0b10aa92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[5]</value>
      <webElementGuid>7d0c0a1f-3ec4-4b8b-aff6-7405dab1a37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'T-SHIRTS' or . = 'T-SHIRTS')]</value>
      <webElementGuid>a9ea8d22-670a-411d-9a68-11aec54fc8ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
