<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Gi hng</name>
   <tag></tag>
   <elementGuidId>a3eb70c5-b820-48e0-9e40-948d46de9b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title-head-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>83d4266f-1304-4011-8b15-087745d2ac8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-head-cart</value>
      <webElementGuid>712d8419-b725-4e6e-93b6-59b52936d984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giỏ hàng</value>
      <webElementGuid>4ffb2ed9-9d8f-47d1-beb0-58c8e59e0443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-wrapper&quot;)/main[1]/section[@id=&quot;cart&quot;]/div[@class=&quot;container&quot;]/div[@id=&quot;cart&quot;]/div[@class=&quot;col-lg-8 col-md-8 col-sm-12 col-xs-12 pd5&quot;]/h1[@class=&quot;title-head-cart&quot;]</value>
      <webElementGuid>300bb98b-bc6a-47b0-baf5-cc6d9321a5a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart']/div/h1</value>
      <webElementGuid>53ae1a8a-fcf3-4308-b610-5b3b55401b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giỏ hàng'])[1]/following::h1[1]</value>
      <webElementGuid>5c882351-30ac-4709-a6d2-aab972c3a438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::h1[1]</value>
      <webElementGuid>1efd4ab1-06de-443c-ac9c-813c639531eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên sản phẩm'])[1]/preceding::h1[1]</value>
      <webElementGuid>d05cee72-befa-4d1e-8de3-ecdcf3b5edc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grown In Love'])[1]/preceding::h1[1]</value>
      <webElementGuid>2d506316-fa72-413f-b6fe-c03e5c080296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>abeca719-d503-4798-a2e3-08e2564b8ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Giỏ hàng' or . = 'Giỏ hàng')]</value>
      <webElementGuid>318c107b-6b4c-42fd-9c65-ff162b295193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
