<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thm vo gi</name>
   <tag></tag>
   <elementGuidId>b27b7952-c7f7-4a27-a0bd-40675753897f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='add-item-form']/div[3]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5063d58c-a0be-4122-b707-1f252938b6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>ea153079-b7a9-414e-b95b-4d9ab1b973f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>5414d55a-5b43-4123-8a77-f2cfb6eaeef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-item-form&quot;)/div[@class=&quot;clearfix&quot;]/button[@class=&quot;btn-style-add add-to-cart&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>aef99ebb-ca2d-4a36-b053-3b7674d67e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-item-form']/div[3]/button/span[2]</value>
      <webElementGuid>b9e9e95a-25e0-40fd-9734-bce6156f4be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[1]/following::span[2]</value>
      <webElementGuid>4ca2e5c5-a409-4ebf-86f6-597cdbb7e1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[2]/following::span[2]</value>
      <webElementGuid>5122524d-f456-4e90-8d17-fac07eafa0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mua ngay'])[1]/preceding::span[2]</value>
      <webElementGuid>f46ad7b1-aaf2-457f-a3fa-01a5598a5e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags:'])[1]/preceding::span[5]</value>
      <webElementGuid>628d877f-46c7-47d1-bbaf-b6fc5ff46128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm vào giỏ']/parent::*</value>
      <webElementGuid>adbeaa37-5828-4441-9267-b9c375a47224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>86103bbc-ff9e-4dd5-b83f-cc9cb2c1c2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>7b6537a5-16c4-4fd5-b607-ab8f6d6b6520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
