<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_giy_dt-width-100 lazyloaded</name>
   <tag></tag>
   <elementGuidId>5c374d92-9b42-467c-8b3c-2fad1dfc28a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img_first > img.dt-width-100.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='group-sale-index']/div[2]/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d29647c-9d8c-4a14-86d9-8d78fc08c0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-width-100 lazyloaded</value>
      <webElementGuid>adf44301-dc90-4926-9cef-817b2abc89f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>85339050-dad7-4b94-adec-ad8df9686bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>3ae36b09-d2bf-41e9-b403-88e0e9ec0b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg</value>
      <webElementGuid>9c451c88-3900-40fe-8b9a-621bcf0428f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg</value>
      <webElementGuid>e2511ea5-549d-4ee3-9ec1-024a6e5b10ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Simple T-Shirt/Cream</value>
      <webElementGuid>e80ff8fa-ebcf-4f68-9ce8-fd4331aace5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-sale-index&quot;)/div[@class=&quot;row box-product-lists&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-sm-4 col-xs-6 product-wrapper product-resize mb30 fixheight&quot;]/div[@class=&quot;product-information&quot;]/div[@class=&quot;product-detail clearfix&quot;]/div[@class=&quot;product-image image-resize&quot;]/a[1]/div[@class=&quot;img_first&quot;]/img[@class=&quot;dt-width-100 lazyloaded&quot;]</value>
      <webElementGuid>24a657fc-6bf8-40ce-97aa-e9a07ebde1e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-sale-index']/div[2]/div/div/div/div/a/div/img</value>
      <webElementGuid>96404470-91e5-4375-acc5-fdb0e849a611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Simple T-Shirt/Cream']</value>
      <webElementGuid>8ae6fd79-d69d-40a0-92f4-44a060ba55a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>f1df8caf-db2e-46df-8a1d-fedff046bf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg' and @alt = 'Simple T-Shirt/Cream']</value>
      <webElementGuid>df9bc357-1d3f-48b7-9b3f-12d2ff3542f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
