<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S in thoi_order-checkout__loading--box show</name>
   <tag></tag>
   <elementGuidId>7e542a01-ecf4-4c59-bdc4-7a13567f3fea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.order-checkout__loading--box.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form_update_location_customer_shipping']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97fca349-3cf4-4ad2-a545-92ddb5cb296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-checkout__loading--box show</value>
      <webElementGuid>c4a0dfdd-9e44-45fe-83d2-4f009721293c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_update_location_customer_shipping&quot;)/div[@class=&quot;order-checkout__loading--box show&quot;]</value>
      <webElementGuid>320008fb-feb7-4e11-87e9-389b25238c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_update_location_customer_shipping']/div</value>
      <webElementGuid>5da511cf-9fba-4a9d-ad9c-26969dba0a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số điện thoại'])[1]/following::div[5]</value>
      <webElementGuid>e693026d-cbcc-47ad-993c-f17018ad5f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Họ và tên'])[1]/following::div[7]</value>
      <webElementGuid>e90e0e82-5c8d-49dd-8bd0-f0b835273cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ'])[1]/preceding::div[2]</value>
      <webElementGuid>99b6e4fb-d39d-4df5-9d57-b15c05229e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tỉnh / thành'])[1]/preceding::div[4]</value>
      <webElementGuid>c80e323b-37d0-4e4e-b379-c0a08406c415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/div/div</value>
      <webElementGuid>c93e62ac-3d88-40d1-ae6e-3825b78ecdd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
