<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Toggle navigation_dt-width-auto</name>
   <tag></tag>
   <elementGuidId>e22307c3-602d-496f-b977-36764517025b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.dt-width-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box-wrapper']/header/div/div/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49516185-e535-41f4-9d3d-38123be26728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-width-auto</value>
      <webElementGuid>db020ad1-3c05-4a8d-9fee-09d83e6bf707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>380</value>
      <webElementGuid>1953dd54-b689-473d-9da0-a18de3c9f1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86</value>
      <webElementGuid>0161d5f5-9970-48b4-9693-4cc38b86161f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//theme.hstatic.net/200000305259/1001044366/14/logo.png?v=34</value>
      <webElementGuid>50f2e7f9-a8f3-418e-afb2-2d68677f8c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Vergency</value>
      <webElementGuid>463a00c9-ad75-466b-9ecb-a9dff16eaf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-wrapper&quot;)/header[@class=&quot;hidden-xs&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;flexbox-grid-default col-xs-12&quot;]/div[@class=&quot;flexbox-content flexbox-align-self-center&quot;]/div[@class=&quot;logo&quot;]/a[1]/img[@class=&quot;dt-width-auto&quot;]</value>
      <webElementGuid>3093a14d-eccd-49b8-b6e4-342d3b6a57be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-wrapper']/header/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>38b316ff-be68-4042-aa20-3944edf596f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Vergency']</value>
      <webElementGuid>8e496122-61be-44ee-86e5-96bd7f3dfae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>cce04103-e35a-4223-a8fb-dd11076e981c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//theme.hstatic.net/200000305259/1001044366/14/logo.png?v=34' and @alt = 'Vergency']</value>
      <webElementGuid>9969e818-6ec6-45d6-9ced-65978873653d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
