<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_giy_dt-width-100 lazyloaded</name>
   <tag></tag>
   <elementGuidId>dc809f79-7a5f-4083-aa0b-7af22e316208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img_first > img.dt-width-100.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='group-sale-index']/div[2]/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7c3fa542-ff43-41a8-a056-0f8863809bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-width-100 lazyloaded</value>
      <webElementGuid>a7147a09-aedb-4856-852b-515f14ada4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>832f0db3-a230-4bd1-86a1-66e006818f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>25078db4-013c-4603-821b-4c29421c46e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg</value>
      <webElementGuid>6c22103a-776b-48fd-b797-f7bf42cad075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg</value>
      <webElementGuid>c4c29d1c-5fe7-4508-99b5-7b3a4e8bb71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Simple T-Shirt/Cream</value>
      <webElementGuid>820e8b70-91fe-4056-9413-7223e9798778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-sale-index&quot;)/div[@class=&quot;row box-product-lists&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-sm-4 col-xs-6 product-wrapper product-resize mb30 fixheight&quot;]/div[@class=&quot;product-information&quot;]/div[@class=&quot;product-detail clearfix&quot;]/div[@class=&quot;product-image image-resize&quot;]/a[1]/div[@class=&quot;img_first&quot;]/img[@class=&quot;dt-width-100 lazyloaded&quot;]</value>
      <webElementGuid>63212751-caf2-4c7d-a6f5-fbdfa82b61b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-sale-index']/div[2]/div/div/div/div/a/div/img</value>
      <webElementGuid>ebd86c8e-bd81-4fb3-b5d2-d5c8170179d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Simple T-Shirt/Cream']</value>
      <webElementGuid>480aed06-ae19-4792-8b02-ec262121c9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>d763205b-061d-46bf-b0e2-116ba5e4d413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/200000305259/product/tee_solid_beige_1_7de152a789824544a8fb0eab449e57e6_large.jpg' and @alt = 'Simple T-Shirt/Cream']</value>
      <webElementGuid>88152aec-d5e0-4d8b-9d81-eaf3d2ee8f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
