<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use (2)</name>
   <tag></tag>
   <elementGuidId>d64c59bd-a5c6-40bf-af72-b5369fe406e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > svg.svg-next-icon.svg-next-icon-size-24 > use</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>6d0e627b-ddd5-4bf0-b4fe-0d706110bb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>d1d0e7cf-6cdc-424c-9c25-fad27c8ebdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#icon-user</value>
      <webElementGuid>bf68f496-9cb1-402e-ba0e-c136b568b605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-wrapper&quot;)/header[@class=&quot;hidden-xs&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;flexbox-grid-default col-xs-12&quot;]/div[@class=&quot;flexbox-content flexbox-align-self-center&quot;]/ul[@class=&quot;icon-control-header text-right&quot;]/li[2]/a[1]/svg[@class=&quot;svg-next-icon svg-next-icon-size-24&quot;]/use[1]</value>
      <webElementGuid>2fc6e1b3-1a95-4b4b-9ea0-14cac0a6e28e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
