<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use (1) (1)</name>
   <tag></tag>
   <elementGuidId>0e55a234-09c9-4237-83ca-e44f68c42e81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a > svg.svg-next-icon.svg-next-icon-size-24 > use</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>2e4faafe-c97b-4ee2-ae42-21a54602bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>3b517143-f277-47bf-8bcf-4f3cd2dbcbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#icon-user</value>
      <webElementGuid>e50f7dc0-01fb-4952-aa38-ac76a7a8e05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-wrapper&quot;)/header[@class=&quot;hidden-xs&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;flexbox-grid-default col-xs-12&quot;]/div[@class=&quot;flexbox-content flexbox-align-self-center&quot;]/ul[@class=&quot;icon-control-header text-right&quot;]/li[2]/a[1]/svg[@class=&quot;svg-next-icon svg-next-icon-size-24&quot;]/use[1]</value>
      <webElementGuid>48f47fc0-9bcc-4364-a569-5504e146de24</webElementGuid>
   </webElementProperties>
</WebElementEntity>
